# Generated by Django 4.2.7 on 2024-01-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['food_name']},
        ),
        migrations.AlterModelOptions(
            name='foodentry',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['date']},
        ),
    ]
