# Generated by Django 4.2.7 on 2024-05-09 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_foodentry_time_alter_goal_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.RenameField(
            model_name='log',
            old_name='user_id',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='FoodEntry',
        ),
        migrations.AddField(
            model_name='meal',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.log'),
        ),
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.meal'),
        ),
    ]
